### ISSUE TITLE
Problem with installing/running the application

### ISSUE THREAD

**Issue by krab1k** [rcsb/strucmotif-search#20]
Hi,

I tried to install the structmotif-search, but I am unable to run it due to a possible dependency issue.

What worked for me:
```bash
$ git clone https://github.com/rcsb/strucmotif-search.git
$ cd strucmotif-search
$ mvn clean install
```
All tests passed successfully. However, I am not able to run the update part first.

```bash
$ cd strucmotif-search-update/dist
$ java -cp strucmotif-update.jar org.rcsb.strucmotif.update.StrucmotifUpdate
```

fails with

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:293)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:118)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:238)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:220)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
        at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:79)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$starting$0(SpringApplicationRunListeners.java:56)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
        at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:56)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:298)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at org.rcsb.strucmotif.update.StrucmotifUpdate.main(StrucmotifUpdate.java:82)
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 17 more

```

Am I missing something here?

```bash
$ java --version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed mode, sharing)

```

**Comment by sbittrich** [comment]
Thanks for the report.
Can you please pull the latest commits and try again?

**Comment by krab1k** [comment]
Worked like a charm. Thank you for the quick response!

If I might have several suggestions for improvement (things that took me a while to understand/fix)

-- `application.properties` settings have to be prefixed with `strucmotif.` I did not find that in any README (found in https://github.com/rcsb/strucmotif-search/issues/1#issuecomment-816033359)
-- In [UPDATE.md](https://github.com/rcsb/strucmotif-search/blob/3415ffdd38cdaba2931800cc2ba26d42b686ba0e/strucmotif-search-update/UPDATE.md), text and examples reference non-existent `MotifSearchUpdate`.  I assume it was replaced by `StrucmotifUpdate`  but I am not sure whether some other changes happened.
-- I would suggest catching exceptions regarding user input and providing the user with a simple error message (and a suggestion of what to do?). For example, when `application.properties` was not set up properly, I ended up with more than a hundred lines of exceptions. It took me a while to find the actual error.

Thank you for your consideration.

**Comment by sbittrich** [comment]
Good points, thanks! Fixed points 1 and 2.

Regarding point 3, stack traces on modern Java tend to be enormous, especially when Stream API or frameworks like Spring are involved and this project has both. If I provide a corrupt properties file, the error message from Spring is surprisingly concise and helpful.

```
2023-04-11T11:20:29.005-07:00  INFO 9894 --- [           main] o.r.strucmotif.update.StrucmotifUpdate   : Starting StrucmotifUpdate using Java 19.0.2 with PID 9894 (/Users/sebastian/IdeaProjects/strucmotif-search/strucmotif-search-update/dist/strucmotif-update.jar started by sebastian in /Users/sebastian/IdeaProjects/strucmotif-search/strucmotif-search-update/dist)
2023-04-11T11:20:29.008-07:00  INFO 9894 --- [           main] o.r.strucmotif.update.StrucmotifUpdate   : No active profile set, falling back to 1 default profile: "default"
2023-04-11T11:20:29.343-07:00  WARN 9894 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'strucmotifUpdate': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'stateRepositoryImpl' defined in URL [jar:file:/Users/sebastian/IdeaProjects/strucmotif-search/strucmotif-search-update/dist/strucmotif-update.jar!/org/rcsb/strucmotif/io/StateRepositoryImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'strucmotifConfig': Could not bind properties to 'StrucmotifConfig' : prefix=strucmotif, ignoreInvalidFields=false, ignoreUnknownFields=true
2023-04-11T11:20:29.348-07:00  INFO 9894 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-04-11T11:20:29.366-07:00 ERROR 9894 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'strucmotif.undefined-assemblies' to boolean:

    Property: strucmotif.undefined-assemblies
    Value: "not-boolean"
    Origin: URL [file:application.properties] - 1:33
    Reason: failed to convert java.lang.String to boolean (caused by java.lang.IllegalArgumentException: Invalid boolean value 'not-boolean')

Action:

Update your application's configuration
```

Can you please share the command that generates the endless stack trace, then I can try to make it a bit more user friendly.

**Comment by krab1k** [comment]
The issue I encountered was not setting the `strucmotif.root-path`, therefore defaulting the directory to non-existent `/opt/data`.

Here, the actual error is mentioned at the very bottom, preceded by a list of errors starting with

```
2023-04-11T20:58:16.751+02:00  WARN 20232 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'strucmotifApplication': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'structureContextBuilder' defined in URL [jar:file:/home/krab1k/Projects/strucmotif-search/strucmotif-search-core/target/strucmotif-search-core-0.18.2-SNAPSHOT.jar!/org/rcsb/strucmotif/domain/query/StructureContextBuilder.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'structureDataProviderImpl': Invocation of init method failed
2023-04-11T20:58:16.765+02:00  INFO 20232 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-04-11T20:58:16.785+02:00 ERROR 20232 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'strucmotifApplication': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'structureContextBuilder' defined in URL [jar:file:/home/krab1k/Projects/strucmotif-search/strucmotif-search-core/target/strucmotif-search-core-0.18.2-SNAPSHOT.jar!/org/rcsb/strucmotif/domain/query/StructureContextBuilder.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'structureDataProviderImpl': Invocation of init method failed

```

**Comment by sbittrich** [comment]
Got it. Not the first time that I'm hearing that, so you're not alone.
Added slightly better error messages with https://github.com/rcsb/strucmotif-search/commit/34eeb9fe3988176af4a9fb6dbb091a910ce5b354.
I might come up with a better long-term solution.

Thanks again for your input. Let me know if anything else comes up, otherwise feel free to close this ticket.

**Comment by krab1k** [comment]
Regarding error handling, I would suggest ending the application gracefully with some error code without propagating the exception to the user (if it's something related to the user input), at least if it's supposed to be run as a command-line app (strucmotif-update).

In any case, everything seems to be working for me now. Thank you.

**Comment by sbittrich** [comment]
Alright, added a more detailed message. Will now exit with:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'strucmotifUpdate' could not be created, the root cause is 'java.nio.file.NoSuchFileException: /doesnt/exist/renumbered.data'.

Action:

Make sure that the directory containing '/doesnt/exist/renumbered.data' exists and this process has the necessary read/write permissions.
```
